---
- name: Ansible
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: vault-decrypt
      shell: "ansible-vault decrypt key.json --vault-password-file pass --output key2.json"
      register: myshell_output
      ignore_errors: True
    - local_action: copy content= dest=file
