---
- name: Ansible
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: copying file with playbook
      copy:
        src: ./key.json
        dest: ./key1.json
        mode: 0777
    - name: vault-decrypt
      shell: "ansible-vault decrypt key1.json --vault-password-file  pass"
      ignore_errors: True
